language: python
python:
- '2.7'
sudo: false
install:
- pip install -U platformio
script:
- platformio run
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hI69fruEtXaicJ9Hb8QiAjGYOzFRswGIcu6gVywgKMqmAuG5DlEFEPSx8iV9DlmZaLQWtPXDhk7xlL+0ADnnECBBqJPBOzLw3TA1I2bfvFf0ulC/zGYnTVNTzkKise4XQO/DtnDy4Qo4pUw860BSxbRwDAvAnbiSsu7Cl/dsUAgyThCxDOUSM3sAvYmZeHDpx/srQmI7DTjs6kEXCyDAnY6TZr/p2gnLuEU2hSFBjYQOZ2dpTpTIMxoGI9etessoFskpvEA8lMZgHXSDOXiT+6cCvLuduM/8kfaYuCdv4ExUxy0XjkCC/8QrvwgL/FbbXeUdekk67D1sCDfqE4Lkws/a0Xn9RX/AoWDMvjOXZIC7ts2k3wPaF6v1IGvANyQHM6LHgFUEAH/7tuiV6wROfZ5HUxtIYB5qGeqhtzIgLZhhnVA6nOLPF8GaUi9+xPU45CT2YjFgyat+sg2V6JNYyHTEeBDSGQhYGbhFYCOYWjCbErrXxAwCdmbWHEgjfL9+JfwHBAZSC7Ixy3vpznx9OzA3qOoqc1C4xkMrC0KBJ3cQe831afqptiHt7aLcEVoVIOeCWkHZPwckgTOjxbXpeXqVtknYegPYJ56KFocYPF2KS2cN1zbzWSYG166R0CcLhQUKMfaRefkFzxPfERNzqfPKNh6pUztbk4QuGVQpAig=
  file: ".pioenvs/teensy31/firmware.elf"
  on:
    repo: barafael/raPID
    tags: true
addons:
  sonarcloud:
    organization: rapid
    token:
      secure: eSqiPjQXzoeAvqDvFiWkwyWFrWBRGvNBfrGDrHKx45qsMCQIxgy14cEUZy8Kj1K+6Mk9mUDZvS+ZZqoW6n7Wkb0pN+ud2/PQo+Sr6kiI/JiQ7zKJPMypxHy4VOgiTqDSNZYVhK2QUtqahFnULE8MYMh5mf1VEAYe/hOmJGNCDSOUmCndMSkWRAIelom1Qqxde+f7u4ImTEqfri+1gY+3tyOrH574Et9mXomRbek9E/oOtyCDsB8//G3AKrbAcP8Cz4VDiAYyBei66t4yvf4bGIExliuvRIyAFHZscP6NsqCIZPMOj+NJbj3/qlOIp+FoXc+fxZdivpDQZtSUQURwdxj/SpZRbLwdbC7u/iJjO4yzbToHLjZAYLD03a20j9gH8QKRPqfPEG2lyW6G0T+sarBT77S2F+4PKriSt1xshOHzJxLGnc/GA3yAnLOutHf1WuFkjkN6oe7CJ/J6g5wRdhOYiAC6UMxVWxLllP1y5A8u2nVLZQpPX+SwEBWcMW0Q240R22U7OnEHIUEqrgi94Adk+iLtPjMIv4CKTVnC+KAbYfWnLm7VH9E4B4opRYr7KhXrbQOE4oFUnSPK3yuGbRFBkmDTiTyy3pdgna6audBJW9Hg9ptn3eK4KgYP4yTfITX597PHUKaqydfY/QX+XWt256GBrmxUE0FNc7s34GY=

cache:
  directories:
    - '$HOME/.sonar/cache'
